# Basic
title: SPACEofPHD
subtitle: A confused looking at the universe.
welcome_message: Do not panic.
description: To boldly go where no man has gone before.
creator: PH

baseurl: /SPACEofPHD

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: 

# The blog button should not be removed.
blog_button:
    title: 全部日志
    description: Visit all blogs

# Navigation buttons in the front page.
nav:
    - {title: 链接：ResearchGate, description: Find me at ResearchGate., url: 'https://www.researchgate.net/profile/Hao_Peng9'}
    - {title: 链接：Google Scholar, description: Find me at Google Scholar., url: 'https://scholar.google.com/citations?user=kOEKfc0AAAAJ&hl=zh-CN'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    # disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
    weibo: 
    github: AstroH-Peng
    twitter: 
    gplus: 
    mail: Astro.H.Peng@onevcat.com
    rss:

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
